// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0GOCfBjuHVZZ9MmpxYshVGxJJdxW-7uk',
    appId: '1:1083431070854:web:74b2c470d4950a697d7507',
    messagingSenderId: '1083431070854',
    projectId: 'qr-app-e3711',
    authDomain: 'qr-app-e3711.firebaseapp.com',
    storageBucket: 'qr-app-e3711.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK5cfYEq5WvjWH8VwEhaK9BfqGCkcXEKA',
    appId: '1:1083431070854:android:9a2dbc7c1c1e4b767d7507',
    messagingSenderId: '1083431070854',
    projectId: 'qr-app-e3711',
    storageBucket: 'qr-app-e3711.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_zH4o8N-LSDWWrrHUjnIALMJWaQzQ9vY',
    appId: '1:1083431070854:ios:a10a8cfbc62382b27d7507',
    messagingSenderId: '1083431070854',
    projectId: 'qr-app-e3711',
    storageBucket: 'qr-app-e3711.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_zH4o8N-LSDWWrrHUjnIALMJWaQzQ9vY',
    appId: '1:1083431070854:ios:a10a8cfbc62382b27d7507',
    messagingSenderId: '1083431070854',
    projectId: 'qr-app-e3711',
    storageBucket: 'qr-app-e3711.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0GOCfBjuHVZZ9MmpxYshVGxJJdxW-7uk',
    appId: '1:1083431070854:web:2f3d5da3275b6eac7d7507',
    messagingSenderId: '1083431070854',
    projectId: 'qr-app-e3711',
    authDomain: 'qr-app-e3711.firebaseapp.com',
    storageBucket: 'qr-app-e3711.appspot.com',
  );

}